#!/bin/bash
# Bundle a Vite project into one self-contained bundle.html with Bun.
# Run from the project root (the folder with package.json and index.html).

set -euo pipefail

# Installed first, before any temp file or directory exists, so every exit path cleans up
WORK_DIR=""
CONFIG_TMP=""
LOCK_DIR=""
cleanup() {
  [ -z "$WORK_DIR" ] || rm -rf "$WORK_DIR"
  [ -z "$CONFIG_TMP" ] || rm -f "$CONFIG_TMP"
  [ -z "$LOCK_DIR" ] || rmdir "$LOCK_DIR" 2>/dev/null || true
}
trap cleanup EXIT

echo "Bundling React app to a single HTML artifact..."

if ! command -v bun &> /dev/null; then
  echo "Error: Bun is not installed. Install it from https://bun.sh and re-run."
  exit 1
fi

if [ ! -f "package.json" ]; then
  echo "Error: No package.json found. Run this script from your project root."
  exit 1
fi

if [ ! -f "index.html" ]; then
  echo "Error: No index.html found in project root."
  echo "   This script requires an index.html entry point."
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

BASE_CONFIG=""
for candidate in vite.config.ts vite.config.mts vite.config.js vite.config.mjs; do
  if [ -f "$candidate" ]; then
    BASE_CONFIG="$candidate"
    break
  fi
done

if [ -z "$BASE_CONFIG" ]; then
  echo "Error: No vite.config.* found. Create the project with init-artifact.sh first."
  exit 1
fi

# The asset inliner parses HTML with parse5 and CSS with css-tree (versions checked 2026-10-06);
# they are installed into the project because the inliner runs from there.
BUNDLE_DEPS=(vite-plugin-singlefile parse5@8.0.1 css-tree@3.2.1)

# True when node_modules already holds the dependency (at the pinned version, if one is given)
dep_installed() {
  local name="${1%@*}" version=""
  [[ "$1" == *@* && "$1" != @* ]] && version="${1##*@}"
  local manifest="node_modules/$name/package.json"
  [ -f "$manifest" ] || return 1
  [ -z "$version" ] || grep -q "\"version\": \"$version\"" "$manifest"
}

# Concurrent runs in one project must not install at the same time: serialize with a lock
# directory (mkdir is atomic) and re-check what is missing once the lock is held.
acquire_lock() {
  local tries=0
  while ! mkdir ".bundle-install.lock" 2>/dev/null; do
    tries=$((tries + 1))
    if [ "$tries" -gt 600 ]; then
      echo "Error: another bundle run holds .bundle-install.lock; remove it if it is stale."
      exit 1
    fi
    sleep 0.2
  done
  LOCK_DIR=".bundle-install.lock"
}

acquire_lock
MISSING_DEPS=()
for dep in "${BUNDLE_DEPS[@]}"; do
  dep_installed "$dep" || MISSING_DEPS+=("$dep")
done
if [ "${#MISSING_DEPS[@]}" -gt 0 ]; then
  echo "Installing bundling dependencies: ${MISSING_DEPS[*]}"
  bun add -d --exact "${MISSING_DEPS[@]}"
fi
rmdir "$LOCK_DIR"
LOCK_DIR=""

# A separate config keeps the normal dev and build setup untouched: it extends the
# project's Vite config (object, promise or function form) and inlines all JS, CSS and assets
# into index.html. Regenerated on every run unless you remove the marker line to customize it.
SINGLEFILE_CONFIG="vite.singlefile.config.ts"
MARKER="// generated by bundle-artifact.sh"
if [ ! -f "$SINGLEFILE_CONFIG" ] || head -n 1 "$SINGLEFILE_CONFIG" | grep -qF "$MARKER"; then
  echo "Writing $SINGLEFILE_CONFIG..."
  CONFIG_TMP="$(mktemp "$SINGLEFILE_CONFIG.XXXXXX")"
  cat > "$CONFIG_TMP" << EOF
$MARKER (remove this line to keep your edits)
import { defineConfig, mergeConfig } from "vite"
import { viteSingleFile } from "vite-plugin-singlefile"
import baseConfig from "./$BASE_CONFIG"

export default defineConfig(async (env) => {
  const base = typeof baseConfig === "function" ? await baseConfig(env) : await baseConfig
  return mergeConfig(base, {
    plugins: [viteSingleFile()],
    build: { emptyOutDir: true },
  })
})
EOF
  chmod 644 "$CONFIG_TMP"
  mv -f "$CONFIG_TMP" "$SINGLEFILE_CONFIG"
  CONFIG_TMP=""
fi

# Every run builds inside its own private work directory (created exclusively), so concurrent
# runs never share output. bundle.html is only replaced after every step succeeded.
WORK_DIR="$(mktemp -d ".bundle-work.XXXXXX")"

echo "Building with Vite..."
# --outDir overrides any build.outDir in a retained custom config
bunx vite build --config "$SINGLEFILE_CONFIG" --outDir "$PWD/$WORK_DIR/dist" --emptyOutDir

if [ ! -f "$WORK_DIR/dist/index.html" ]; then
  echo "Error: the build produced no index.html"
  exit 1
fi

echo "Inlining public assets..."
# Run a copy from inside the project so it resolves the parsers from the project's node_modules
cp "$SCRIPT_DIR/inline-local-assets.mjs" "$WORK_DIR/inline-local-assets.mjs"
bun "$WORK_DIR/inline-local-assets.mjs" "$WORK_DIR/dist" "$WORK_DIR/bundle.html" "$PWD"

mv -f "$WORK_DIR/bundle.html" bundle.html
chmod 644 bundle.html

FILE_SIZE=$(du -h bundle.html | cut -f1)

echo ""
echo "Bundle complete."
echo "Output: bundle.html ($FILE_SIZE)"
echo ""
echo "You can now use this single HTML file as an artifact in Claude conversations."
echo "To test locally: open bundle.html in your browser"
