#!/bin/bash
# Bundle a Vite project into one self-contained bundle.html with Bun.
# Run from the project root (the folder with package.json and index.html).

set -euo pipefail

# Installed first, before any temp file or directory exists, so every exit path cleans up
WORK_DIR=""
CONFIG_TMP=""
LOCK_DIR=""
cleanup() {
  [ -z "$WORK_DIR" ] || rm -rf "$WORK_DIR"
  [ -z "$CONFIG_TMP" ] || rm -f "$CONFIG_TMP"
  [ -z "$LOCK_DIR" ] || rm -rf "$LOCK_DIR"
}
trap cleanup EXIT
# Turn termination signals into a normal exit so the EXIT trap (lock and temp cleanup) still runs
trap 'exit 130' INT
trap 'exit 143' TERM
trap 'exit 129' HUP

echo "Bundling React app to a single HTML artifact..."

if ! command -v bun &> /dev/null; then
  echo "Error: Bun is not installed. Install it from https://bun.sh and re-run."
  exit 1
fi

if [ ! -f "package.json" ]; then
  echo "Error: No package.json found. Run this script from your project root."
  exit 1
fi

if [ ! -f "index.html" ]; then
  echo "Error: No index.html found in project root."
  echo "   This script requires an index.html entry point."
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

BASE_CONFIG=""
for candidate in vite.config.ts vite.config.mts vite.config.js vite.config.mjs; do
  if [ -f "$candidate" ]; then
    BASE_CONFIG="$candidate"
    break
  fi
done

if [ -z "$BASE_CONFIG" ]; then
  echo "Error: No vite.config.* found. Create the project with init-artifact.sh first."
  exit 1
fi

# The asset inliner parses HTML with parse5 and CSS with css-tree (versions checked 2026-10-06);
# they are installed into the project because the inliner runs from there.
BUNDLE_DEPS=(vite-plugin-singlefile parse5@8.0.1 css-tree@3.2.1)

# True when node_modules already holds the dependency (at the pinned version, if one is given)
dep_installed() {
  local name="${1%@*}" version=""
  [[ "$1" == *@* && "$1" != @* ]] && version="${1##*@}"
  local manifest="node_modules/$name/package.json"
  [ -f "$manifest" ] || return 1
  [ -z "$version" ] || grep -q "\"version\": \"$version\"" "$manifest"
}

# Concurrent runs in one project must not install at the same time: serialize with a lock
# directory (mkdir is atomic) and re-check what is missing once the lock is held. The lock records
# its owner (pid and process start time); a lock whose owner is gone (for example after kill -9)
# is stale and gets taken over.
LOCK_PATH=".bundle-install.lock"

process_start() {
  ps -o lstart= -p "$1" 2>/dev/null | sed 's/^ *//; s/ *$//'
}

lock_is_stale() {
  local owner="$LOCK_PATH/owner" pid started
  if [ ! -f "$owner" ]; then
    # The owner may still be about to write its record; only call it stale once the lock is old
    [ -n "$(find "$LOCK_PATH" -maxdepth 0 -mmin +1 2>/dev/null)" ]
    return
  fi
  read -r pid started < <(head -n 1 "$owner" | awk '{pid=$1; $1=""; sub(/^ /,""); print pid, $0}') || return 0
  [ -n "$pid" ] || return 0
  kill -0 "$pid" 2>/dev/null || return 0
  [ "$(process_start "$pid")" = "$started" ] || return 0
  return 1
}

acquire_lock() {
  local tries=0
  while ! mkdir "$LOCK_PATH" 2>/dev/null; do
    if lock_is_stale; then
      # rename is atomic: of several runs recovering the same stale lock, exactly one wins
      if mv "$LOCK_PATH" "$LOCK_PATH.stale.$$" 2>/dev/null; then
        rm -rf "$LOCK_PATH.stale.$$"
        echo "Removed a stale install lock."
      fi
      continue
    fi
    tries=$((tries + 1))
    if [ "$tries" -gt 600 ]; then
      echo "Error: another bundle run holds $LOCK_PATH (see $LOCK_PATH/owner)."
      exit 1
    fi
    sleep 0.2
  done
  LOCK_DIR="$LOCK_PATH"
  echo "$$ $(process_start $$)" > "$LOCK_DIR/owner"
}

acquire_lock
MISSING_DEPS=()
for dep in "${BUNDLE_DEPS[@]}"; do
  dep_installed "$dep" || MISSING_DEPS+=("$dep")
done
if [ "${#MISSING_DEPS[@]}" -gt 0 ]; then
  echo "Installing bundling dependencies: ${MISSING_DEPS[*]}"
  bun add -d --exact "${MISSING_DEPS[@]}"
fi
rm -rf "$LOCK_DIR"
LOCK_DIR=""

# A separate config keeps the normal dev and build setup untouched: it extends the
# project's Vite config (object, promise or function form) and inlines all JS, CSS and assets
# into index.html. Regenerated on every run unless you remove the marker line to customize it.
SINGLEFILE_CONFIG="vite.singlefile.config.ts"
MARKER="// generated by bundle-artifact.sh"
if [ ! -f "$SINGLEFILE_CONFIG" ] || head -n 1 "$SINGLEFILE_CONFIG" | grep -qF "$MARKER"; then
  echo "Writing $SINGLEFILE_CONFIG..."
  CONFIG_TMP="$(mktemp "$SINGLEFILE_CONFIG.XXXXXX")"
  cat > "$CONFIG_TMP" << EOF
$MARKER (remove this line to keep your edits)
import { defineConfig, mergeConfig } from "vite"
import { viteSingleFile } from "vite-plugin-singlefile"
import baseConfig from "./$BASE_CONFIG"

export default defineConfig(async (env) => {
  const base = typeof baseConfig === "function" ? await baseConfig(env) : await baseConfig
  return mergeConfig(base, {
    plugins: [viteSingleFile()],
    build: { emptyOutDir: true },
  })
})
EOF
  chmod 644 "$CONFIG_TMP"
  mv -f "$CONFIG_TMP" "$SINGLEFILE_CONFIG"
  CONFIG_TMP=""
fi

# Every run builds inside its own private work directory (created exclusively), so concurrent
# runs never share output. bundle.html is only replaced after every step succeeded.
WORK_DIR="$(mktemp -d ".bundle-work.XXXXXX")"

echo "Building with Vite..."
# --outDir overrides any build.outDir in a retained custom config
bunx vite build --config "$SINGLEFILE_CONFIG" --outDir "$PWD/$WORK_DIR/dist" --emptyOutDir

if [ ! -f "$WORK_DIR/dist/index.html" ]; then
  echo "Error: the build produced no index.html"
  exit 1
fi

echo "Inlining public assets..."
# Run a copy from inside the project so it resolves the parsers from the project's node_modules
cp "$SCRIPT_DIR/inline-local-assets.mjs" "$WORK_DIR/inline-local-assets.mjs"
bun "$WORK_DIR/inline-local-assets.mjs" "$WORK_DIR/dist" "$WORK_DIR/bundle.html" "$PWD"

mv -f "$WORK_DIR/bundle.html" bundle.html
chmod 644 bundle.html

FILE_SIZE=$(du -h bundle.html | cut -f1)

echo ""
echo "Bundle complete."
echo "Output: bundle.html ($FILE_SIZE)"
echo ""
echo "You can now use this single HTML file as an artifact in Claude conversations."
echo "To test locally: open bundle.html in your browser"
